### ISSUE TITLE
Nieuwe versie Climate

### ISSUE THREAD

**Issue by stgm** [minprog/climate#5]
Todo:

- [x] Grafieken duidelijk uitleggen en labelen, assen op jaartallen. Mag een beetje fancy.
- [x] Data is temperatuur x 10 (dus -10 betekent -1 graad), dit is nu niet gecorrigeerd in voorbeelduitwerking en grafieken.
- [x] Zorgvuldig elk (theoretisch) detail van de opdracht uitleggen, voorbeeld was de formule voor mean centering.
- [x] Alle gegeven code uitleggen.
- [x] Assertions voor alle opdrachten (waar relevant), zie ook discussie.

Discussie:

- [x] Moet de preprocessing niet in een aparte python-file (ipv in de notebook) omdat hier echt met files wegschrijven wordt gewerkt?
- [ ] Als we met een vast databestand werken (geen kleine versie) dan kunnen er hardcoded waarden in de assertions (bv. mean=7.6). Als we ook kleine voorbeeldfiles gebruiken moeten we kijken hoe we dit testen en combineren met de assertions.

**Comment by Jelleas** [comment]
Ik zat te denken om aan het begin van het notebook een constante in te stellen:

```
DATAFILE = "/bigdatafile.csv"
```

Dan kunnen we later in de checks daarop checken.

**Comment by Jelleas** [comment]
> Moet de preprocessing niet in een aparte python-file (ipv in de notebook) omdat hier echt met files wegschrijven wordt gewerkt?

Als we met meerdere databestanden gaan werken moet dit script alvast een beetje ge-scaffold worden. Iets als

```Py
path = "rawdata"
fixed_path = "data"
for filename in os.listdir(path):
     fix(f"{fixed_path}/{filename}",  f"{path}{filename.replace('txt', 'csv')}")
```

Sowieso, als we met meerdere databestanden geen werken en er ook die tijdelijke tussenoplossingen bestaan (`climate1.csv`, `climate2.csv`, etc.) om al die tijdelijke dan ook weg te gooien aan het eind. `os.remove('climate1.csv')`. Anders wordt het snel onoverzichtelijk.

**Comment by Jelleas** [comment]
Misschien datum opsplitsing en temperatuur fixen meenemen in preprocessing?

```
DATA,TX
15072012,300
```

=>

```
DAY,MONTH,YEAR,TEMP
15,07,2012,30.0
```

**Comment by stgm** [comment]
Misschien het script zelfs met een command-line argument. En misschien moet het script wel altijd to_process.csv uitvoeren (hardcoded), die steeds weer overschreven wordt. Dan heb je altijd maar één tijdelijk bestand.

**Comment by stgm** [comment]
> Misschien datum opsplitsing en temperatuur fixen meenemen in preprocessing?

Ja, zodat je in de notebook eigenlijk geen enkele transformatie meer hoeft te doen, klinkt logisch.

**Comment by Jelleas** [comment]
```Py
import argparse
import os

parser = argparse.ArgumentParser(description='Preprocess data files.')
parser.add_argument('paths', metavar='N', type=str, nargs='*',
                    help='all datafiles to preprocess')

args = parser.parse_args()

paths = args.paths
if not paths:
     paths = [f"rawdata/{filename}" for filename in os.listdir("rawdata")]

if not os.path.exists("data"):
    os.mkdir("data")

for path in paths:
     dest = f"data/{os.path.basename(path)}"
     fix(path, dest)
```

**Comment by robinlangerak** [comment]
Ik heb:

- de grafeken aangepast zodat ze nu correct de jaartallen laten zien
- meer uitleg toegevoegd bij de technische stukken
- het stuk over mean centering weggehaald omdat ik bij het schrijven van de uitwerking van opgave 4 niet meehielp en dat was toch het idee van het stuk over mean centering. Opgave 4 is daarmee wat zwaarder geworden, maar dat vind ik niet erg want het past beter in de opbouw van de opgaven.

Te doen:

- code kritisch nakijken
- Preprocessing aanpassen zoals hierboven aangegeven (ik ben het er wel mee eens).
- meer asserts toevoegen

**Comment by robinlangerak** [comment]
Qua een apart notebook voor de pre-processing: ben ik niet voor omdat in mijn ogen pre-processing een onlosmakelijk onderdeel moet zijn van data-analyse. Bovendien verstoort het de opbouw van de huidige notebook...

**Comment by robinlangerak** [comment]
Het schiet me net te binnen waarom ik de uitsplitsing van de datum in jaar, maand en dag niet had opgenomen in de preprocessing: die stap is niet eenvoudig met de hand te doen, mat als gevolg dat de hele opgave in het water valt als je daar een fout maakt...
